src/Entity/Boutique.php
<?php

namespace App\Entity;

use App\Repository\BoutiqueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BoutiqueRepository::class)]
class Boutique
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Adresse = null;

    /**
     * @var Collection<int, Produit>
     */
    #[ORM\OneToMany(targetEntity: Produit::class, mappedBy: 'boutique', cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $produits;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): static
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    /**
     * @return Collection<int, Produit>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): static
    {
        if (!$this->produits->contains($produit)) {
            $this->produits->add($produit);
            $produit->setBoutique($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): static
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getBoutique() === $this) {
                $produit->setBoutique(null);
            }
        }

        return $this;
    }
}

src/Form/BoutiqueType.php
<?php

namespace App\Form;

use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use App\Entity\Boutique;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BoutiqueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Adresse')
            ->add('Send', SubmitType::class )

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Boutique::class,
        ]);
    }
}

src/Controller/BoutiqueController.php
<?php

namespace App\Controller;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Boutique;
use App\Form\BoutiqueType;
use App\Form\AddEditFormType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\BoutiqueRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class BoutiqueController extends AbstractController
{
    #[Route('/boutique', name: 'app_boutique')]
    public function listboutique(BoutiqueRepository $boutiqueRepository)
    {   
        
        $boutiquesDB = $boutiqueRepository->findAll();

        return $this->render('boutique/index.html.twig', [
            'boutiques'=> $boutiquesDB,

           
        ]);
    }


    

    #[Route('/boutique/ajout', name: 'app_boutique_ajout')]
    public function addAuthorform(ManagerRegistry $mr,BoutiqueRepository $repo,Request $req): Response
    {
        $boutique = new Boutique();
        $forum= $this->createForm(BoutiqueType::class,$boutique);
        $forum->handleRequest($req);
        if($forum->isSubmitted()&&$forum->isValid())
        {
            $em=$mr->getManager();
            $em->persist($boutique);
            $em->flush();
            return $this->redirectToRoute('app_boutique');
        }
      
        return $this->render('boutique/ajout.html.twig', ['form'=>$forum->createView(),]);
    }

    #[Route('/boutique/modier/{id}', name: 'app_boutique_modifier')]
    public function editAuthor($id, Request $request, BoutiqueRepository $boutiqueRepository, EntityManagerInterface $em){
        $boutique= $boutiqueRepository->find($id);
        $form= $this->createForm(BoutiqueType::class, $boutique);
        $form->handleRequest($request);
        if($form->isSubmitted()){
            //$em->persist($author);
            $em->flush();
            return $this->redirectToRoute('app_boutique');
        }
        return $this->render('boutique/ajout.html.twig',[
            'title' => 'Update Boutique',
            'form' => $form
        ]);
    }
    #[Route('/boutique/details/{id}', name: 'app_boutique_details')]
    public function boutiqueDetails($id, BoutiqueRepository $boutiqueRepository){
        $boutique = $boutiqueRepository->find($id);


        return $this->render('boutique/details.html.twig',[
            'boutique' => $boutique
        ]);
    }

    #[Route('/boutique/supprimer/{id}', name: 'app_boutique_supprimer')]
    public function deleteAuthor($id, BoutiqueRepository $boutiqueRepository, EntityManagerInterface $em){
        $boutique= $boutiqueRepository->find($id);
        $em->remove($boutique);
        $em->flush();
        return $this->redirectToRoute('app_boutique');
        //return new Response('Author deleted');

    }
}

templates/boutique/ajout.html.twig
{{form(form)}}

templates/boutique/details.html.twig
                <h2>{{ boutique.nom |upper }}</h2>
                <p>prix: {{ boutique.adresse }}</p>
        <a href="{{path('app_boutique')}}">go back</a>    

templates/boutique/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">

     <ul>
        {% for boutique in boutiques %}
            <li>
                
                <h2>{{ boutique.nom |upper }}</h2>
                <p>Adresse: {{ boutique.adresse }}</p>
                
                                    <a href="{{path('app_boutique_details',{ id: boutique.id })}}">Details</a>    

                 
                    <a href="{{path('app_boutique_modifier',{ id: boutique.id })}}">Update</a>
                    <a href="{{path('app_boutique_supprimer',{ id: boutique.id })}}">Delete</a>    
            </li>
        {% else %}
            <li>No authors available.</li>
        {% endfor %}
    </ul>
        <a href="{{path('app_boutique_ajout')}}">Ajouter nouvau boutique</a>    

</div>
{% endblock %}

templates/boutique/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BoutiqueController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/Users/coola/Desktop/symfony/FirstProjectt/src/Controller/BoutiqueController.php</code></li>
        <li>Your template at <code>C:/Users/coola/Desktop/symfony/FirstProjectt/templates/boutique/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}